### PR TITLE
display timezone and weekday in plot

### LINKED ISSUE #210: timezone information in results plot
- the result we are producing are given in datetime zone "UTC", the operator needs to know this. This could be added to the "tooltip" when the user hovers the mouse over the line.
- it would be beneficial to add a vertical line to the results plot that shows the current datetime in UTC
- is it possible to add which weekday it is to top of results plot?

### PR DESCRIPTION
**Pull request by KristianKjerstad**
* display timezone as part of the plot
* display weekday in plot ticks

closes #210

### CODE REVIEW

**Review by soofstad — CHANGES_REQUESTED** [review]
load TZ from timestamp. Don't assume

**Comment by KristianKjerstad** [comment]
shading for plot / vertical line:


<VictoryAxis
  label="Label"
  //theme={VictoryTheme.material}
   //tickValues={[3]}
  //tickCount={4}
  style={{
    axis: {stroke: "#756f6a", opacity: 0.2},

    grid: {stroke: ({ tick }) => tick > 0.4 ? "red" : "grey"},
	ticks: {stroke: "blue"}

  }}
/>

**Comment by KristianKjerstad** [comment]
image

**Comment by KristianKjerstad** [comment]
image

**Review by soofstad — APPROVED** [review]

**Pull request merged**
